global:
  smtp_smarthost: 'smtp.gmail.com:587' # Cấu hình SMTP server của bạn
  smtp_from: 'your-email@gmail.com'
  smtp_auth_username: 'your-email@gmail.com'
  smtp_auth_password: 'your-app-password' # Sử dụng App Password cho Gmail

route:
  receiver: "email-notifications"
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 1h
  routes:
  - match:
      severity: critical
    receiver: "email-notifications"
    group_wait: 0s

receivers:
- name: "email-notifications"
  email_configs:
  - to: 'admin-team@company.com'
    send_resolved: true
    subject: '[{{ .Status | toUpper }}] {{ .GroupLabels.alertname }}'
    text: >-
      {{ range .Alerts }}
      {{ .Annotations.description }}
      {{ end }}