global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'alert-system@yourdomain.com'
  smtp_auth_username: 'duongphat521@gmail.com'
  smtp_auth_password: 'jmbj dknp dubj itfe'
  smtp_require_tls: true

route:
  receiver: 'admin-email'
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 1h

receivers:
  - name: 'admin-email'
    email_configs:
      - to: 'admin@yourdomain.com'
        send_resolved: false
        html: |
          <h2>Cảnh báo Hệ thống</h2>
          <p><strong>Alert:</strong> {{ .GroupLabels.alertname }}</p>
          <p><strong>Mức độ:</strong> {{ .CommonLabels.severity }}</p>
          <p><strong>Chi tiết:</strong> {{ .CommonAnnotations.description }}</p>