groups:
  - name: kafka_dlq_alerts
    rules:
      - alert: DeadLetterQueueNotEmpty
        expr: rate(kafka_topic_partition_current_offset{topic="dead_letter"}[1m]) > 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Phát hiện message mới trong Dead Letter Queue"
          description: "Topic dead_letter đang nhận thêm message thất bại. Rate: {{ $value }} messages/s. Vui lòng kiểm tra hệ thống!"